// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: interchain_security/consumergov/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgConsumerGovProposal is a governance proposal that affects the DEX consumer chain.
type MsgConsumerGovProposal struct {
	Title       string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ConsumerId  string `protobuf:"bytes,3,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	Action      string `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Payload     []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Authority   string `protobuf:"bytes,6,opt,name=authority,proto3" json:"authority,omitempty"`
}

func (m *MsgConsumerGovProposal) Reset()         { *m = MsgConsumerGovProposal{} }
func (m *MsgConsumerGovProposal) String() string { return proto.CompactTextString(m) }
func (*MsgConsumerGovProposal) ProtoMessage()    {}
func (*MsgConsumerGovProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5114fafef2098c2, []int{0}
}
func (m *MsgConsumerGovProposal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConsumerGovProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConsumerGovProposal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConsumerGovProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConsumerGovProposal.Merge(m, src)
}
func (m *MsgConsumerGovProposal) XXX_Size() int {
	return m.Size()
}
func (m *MsgConsumerGovProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConsumerGovProposal.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConsumerGovProposal proto.InternalMessageInfo

func (m *MsgConsumerGovProposal) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MsgConsumerGovProposal) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *MsgConsumerGovProposal) GetConsumerId() string {
	if m != nil {
		return m.ConsumerId
	}
	return ""
}

func (m *MsgConsumerGovProposal) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *MsgConsumerGovProposal) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *MsgConsumerGovProposal) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

// Define the response message
type MsgConsumerGovProposalResponse struct {
}

func (m *MsgConsumerGovProposalResponse) Reset()         { *m = MsgConsumerGovProposalResponse{} }
func (m *MsgConsumerGovProposalResponse) String() string { return proto.CompactTextString(m) }
func (*MsgConsumerGovProposalResponse) ProtoMessage()    {}
func (*MsgConsumerGovProposalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a5114fafef2098c2, []int{1}
}
func (m *MsgConsumerGovProposalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgConsumerGovProposalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgConsumerGovProposalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgConsumerGovProposalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgConsumerGovProposalResponse.Merge(m, src)
}
func (m *MsgConsumerGovProposalResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgConsumerGovProposalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgConsumerGovProposalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgConsumerGovProposalResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgConsumerGovProposal)(nil), "interchain_security.consumergov.v1.MsgConsumerGovProposal")
	proto.RegisterType((*MsgConsumerGovProposalResponse)(nil), "interchain_security.consumergov.v1.MsgConsumerGovProposalResponse")
}

func init() {
	proto.RegisterFile("interchain_security/consumergov/v1/tx.proto", fileDescriptor_a5114fafef2098c2)
}

var fileDescriptor_a5114fafef2098c2 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x31, 0xeb, 0xd3, 0x40,
	0x18, 0xc6, 0x7b, 0xd6, 0x56, 0x7a, 0x15, 0x87, 0xb3, 0xd4, 0x98, 0x21, 0x86, 0x4e, 0xa5, 0xd2,
	0x1c, 0x55, 0x74, 0x28, 0x2e, 0xd6, 0x41, 0x1c, 0x0a, 0x12, 0xc1, 0xc1, 0xa5, 0x5c, 0x2f, 0x47,
	0x7a, 0xd0, 0xe4, 0xc2, 0xbd, 0x97, 0xd0, 0x38, 0x89, 0x9f, 0xc0, 0xc5, 0x6f, 0xe0, 0x07, 0xe8,
	0xe0, 0x87, 0x70, 0x2c, 0x4e, 0x8e, 0xd2, 0x0e, 0x1d, 0xfc, 0x12, 0xd2, 0xa4, 0xa1, 0x15, 0x02,
	0xc2, 0x7f, 0xfc, 0xbd, 0xcf, 0xf3, 0xdc, 0xbd, 0xef, 0xdd, 0x8b, 0x1f, 0xcb, 0xd8, 0x08, 0xcd,
	0x57, 0x4c, 0xc6, 0x0b, 0x10, 0x3c, 0xd5, 0xd2, 0xe4, 0x94, 0xab, 0x18, 0xd2, 0x48, 0xe8, 0x50,
	0x65, 0x34, 0x9b, 0x50, 0xb3, 0xf1, 0x12, 0xad, 0x8c, 0x22, 0x83, 0x1a, 0xb3, 0x77, 0x65, 0xf6,
	0xb2, 0x89, 0xfd, 0x80, 0x2b, 0x88, 0x14, 0xd0, 0x08, 0xc2, 0x53, 0x36, 0x82, 0xb0, 0x0c, 0xdb,
	0x0f, 0x4b, 0x61, 0x51, 0x10, 0x2d, 0xa1, 0x94, 0x06, 0x7f, 0x10, 0xee, 0xcf, 0x21, 0x7c, 0x75,
	0x3e, 0xe9, 0xb5, 0xca, 0xde, 0x6a, 0x95, 0x28, 0x60, 0x6b, 0xd2, 0xc3, 0x2d, 0x23, 0xcd, 0x5a,
	0x58, 0xc8, 0x45, 0xc3, 0x8e, 0x5f, 0x02, 0x71, 0x71, 0x37, 0x10, 0xc0, 0xb5, 0x4c, 0x8c, 0x54,
	0xb1, 0x75, 0xab, 0xd0, 0xae, 0x4b, 0xe4, 0x11, 0xee, 0x56, 0x8d, 0x2d, 0x64, 0x60, 0x35, 0x0b,
	0x07, 0xae, 0x4a, 0x6f, 0x02, 0xd2, 0xc7, 0x6d, 0xc6, 0x8b, 0xf4, 0xed, 0x42, 0x3b, 0x13, 0xb1,
	0xf0, 0x9d, 0x84, 0xe5, 0x6b, 0xc5, 0x02, 0xab, 0xe5, 0xa2, 0xe1, 0x5d, 0xbf, 0x42, 0xf2, 0x1c,
	0x77, 0x58, 0x6a, 0x56, 0xea, 0x34, 0xb5, 0xd5, 0x3e, 0x85, 0x66, 0xd6, 0xcf, 0xef, 0xe3, 0xde,
	0x79, 0x94, 0x97, 0x41, 0xa0, 0x05, 0xc0, 0x3b, 0xa3, 0x65, 0x1c, 0xfa, 0x17, 0xeb, 0xf4, 0xde,
	0xe7, 0xe3, 0x76, 0x74, 0xe1, 0x81, 0x8b, 0x9d, 0xfa, 0x61, 0x7d, 0x01, 0x89, 0x8a, 0x41, 0x3c,
	0xf9, 0x86, 0x70, 0x73, 0x0e, 0x21, 0xf9, 0x8a, 0xf0, 0xfd, 0xba, 0x47, 0x99, 0x7a, 0xff, 0xff,
	0x08, 0xaf, 0xfe, 0x0e, 0x7b, 0x76, 0xf3, 0x6c, 0xd5, 0x9f, 0xdd, 0xfa, 0x74, 0xdc, 0x8e, 0xd0,
	0xec, 0xfd, 0x8f, 0xbd, 0x83, 0x76, 0x7b, 0x07, 0xfd, 0xde, 0x3b, 0xe8, 0xcb, 0xc1, 0x69, 0xec,
	0x0e, 0x4e, 0xe3, 0xd7, 0xc1, 0x69, 0x7c, 0x78, 0x11, 0x4a, 0xb3, 0x4a, 0x97, 0x1e, 0x57, 0x11,
	0x8d, 0x18, 0x8b, 0xf3, 0xf1, 0x26, 0xff, 0x48, 0x25, 0x07, 0x9a, 0x3d, 0xa3, 0x1b, 0xca, 0x79,
	0x46, 0x13, 0xad, 0x32, 0x19, 0x08, 0xfd, 0xcf, 0xb2, 0x99, 0x3c, 0x11, 0xb0, 0x6c, 0x17, 0x5b,
	0xf1, 0xf4, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xbf, 0x4c, 0x3f, 0x9c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// ConsumerGovProposal creates a new governance proposal.
	ConsumerGovProposal(ctx context.Context, in *MsgConsumerGovProposal, opts ...grpc.CallOption) (*MsgConsumerGovProposalResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ConsumerGovProposal(ctx context.Context, in *MsgConsumerGovProposal, opts ...grpc.CallOption) (*MsgConsumerGovProposalResponse, error) {
	out := new(MsgConsumerGovProposalResponse)
	err := c.cc.Invoke(ctx, "/interchain_security.consumergov.v1.Msg/ConsumerGovProposal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// ConsumerGovProposal creates a new governance proposal.
	ConsumerGovProposal(context.Context, *MsgConsumerGovProposal) (*MsgConsumerGovProposalResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ConsumerGovProposal(ctx context.Context, req *MsgConsumerGovProposal) (*MsgConsumerGovProposalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConsumerGovProposal not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ConsumerGovProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgConsumerGovProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ConsumerGovProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interchain_security.consumergov.v1.Msg/ConsumerGovProposal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ConsumerGovProposal(ctx, req.(*MsgConsumerGovProposal))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "interchain_security.consumergov.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsumerGovProposal",
			Handler:    _Msg_ConsumerGovProposal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interchain_security/consumergov/v1/tx.proto",
}

func (m *MsgConsumerGovProposal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConsumerGovProposal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConsumerGovProposal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Action) > 0 {
		i -= len(m.Action)
		copy(dAtA[i:], m.Action)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Action)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ConsumerId) > 0 {
		i -= len(m.ConsumerId)
		copy(dAtA[i:], m.ConsumerId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ConsumerId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Description) > 0 {
		i -= len(m.Description)
		copy(dAtA[i:], m.Description)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Description)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Title) > 0 {
		i -= len(m.Title)
		copy(dAtA[i:], m.Title)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Title)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgConsumerGovProposalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgConsumerGovProposalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgConsumerGovProposalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgConsumerGovProposal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Title)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ConsumerId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Action)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgConsumerGovProposalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgConsumerGovProposal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConsumerGovProposal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConsumerGovProposal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Title", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Title = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Action", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Action = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgConsumerGovProposalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgConsumerGovProposalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgConsumerGovProposalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
